# Generated by Django 5.1.1 on 2025-04-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hafez",
            fields=[
                (
                    "urn",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("section", models.TextField()),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "hafez",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Khayyam",
            fields=[
                (
                    "urn",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("section", models.TextField()),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "khayyam",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Moulavi",
            fields=[
                (
                    "urn",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("section", models.TextField()),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "moulavi",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GolestanHikayat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bab", models.CharField(max_length=50)),
                ("hekayat", models.IntegerField()),
                ("content", models.TextField()),
            ],
            options={
                "db_table": "golestan_hikayat",
            },
        ),
    ]
